baseURL               = "https://nav.acoi.top/"
languageCode          = "zh-CN"
title                 = "奥创学堂网址导航"
theme                 = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"				# 站点静态文件保存目录


[params]
    author        = "奥创学堂"
    description   = "奥创学堂网址导航"
    repository    = ""  
    enablePreLoad = true					# 网站完全打开前预加载动画
    textPreLoad   = "奥创学堂网址导航"				# 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = false					# 默认展开左侧边导航栏
    logosPath     = "assets/images/logos"			# 网站每个导航地址logo存放地址
    defaultLogo   = "assets/images/logos/default.webp"		# logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    nightMode     = false					# 默认站点为深色(夜间)模式
    yiyan         = false                         		# 默认启用一言服务
    fancybox      = true                                        # 使用 Fancybox 实现图片灯箱/放大功能

[params.seo]    
    baiduhmid       = '87dc8d6d3d382ce16435e844f6eb9d9c'	# 百度统计 hm.src 的 ID
    baiduSiteVer    = ''			# 百度HTML标签验证(baidu-site-verification)
    tj51laid        = ''                        		# 51.LA 网站统计
    tj51lack        = ''
    GoogleAdsClient = ''					# Google AdSense 

[params.qweather]
    key = ""

[params.images]
    favicon           = "assets/images/奥-源样明宋体Heavy-无底蓝字.png"
    searchImageL      = "assets/images/bg-space.png"		# 搜索部分浅色背景图
    searchImageD      = "assets/images/bg-space.png"		# 搜索部分深色背景图
    logoExpandLight   = "assets/images/奥创学堂-源样明宋体Heavy-无底蓝字.png"
    logoExpandDark    = "assets/images/奥创学堂-源样明宋体Heavy-无底白字.png"
    logoCollapseLight = "assets/images/奥-源样明宋体Heavy-无底蓝字.png"
    logoCollapseDark  = "assets/images/奥-源样明宋体Heavy-无底白字.png"
    qrcode            = "assets/images/导航活码.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '本站内容源自互联网，如有内容侵犯了你的权益，请联系删除相关内容，联系邮箱：official@ultraoi.cn <br/>&copy; {year} By 奥创学堂| [粤ICP备2024325364号-1](http://beian.miit.gov.cn/)<br/>'
